using UnityEngine;


[RequireComponent(typeof(Collider2D))] //basically just to ensure it has a collider for trigger detection
public class SortGroup : MonoBehaviour
{
    [SerializeField] private string type = default;
    private Vector3 originalScale;

    public GameObject objTouching;


    private void Start()
    {
        originalScale = transform.localScale;
    }

    private void OnTriggerEnter2D(Collider2D col)
    {
        objTouching = col.gameObject;
        objTouching.GetComponent<WorldDraggable>().sortGroup = this;
        transform.localScale = originalScale * 1.2f; // enlarge visually when hovering over with file
    }

    private void OnTriggerExit2D(Collider2D col)
    {
        objTouching = null;
        transform.localScale = originalScale; // reset scale
    }


    public void TrySort(WorldDraggable draggable)
    {
        if (draggable.type == type)
        {
            Debug.Log("Correctly sorted object of type: " + type);
            SFXManager.Instance.PlaySFX("correct");
        }
        else
        {
            GameManager.numIncorrect++;
            SFXManager.Instance.PlaySFX("incorrect");
        }

        Destroy(draggable.gameObject);
        WorldDraggable.ActiveFiles--;
    }
}
